Finally compiled 0AD 0.28

diff --git a/0ad-git/gamemoderun_mangohud.patch b/0ad-git/gamemoderun_mangohud.patch
--- a/0ad-git/gamemoderun_mangohud.patch
+++ b/0ad-git/gamemoderun_mangohud.patch
@@ -1,27 +1,22 @@
---- a/build/resources/0ad.sh	2026-01-18 23:38:28.693460280 -0500
-+++ b/build/resources/0ad.sh	2026-01-18 23:36:32.725715459 -0500
-@@ -1,9 +1,20 @@
+--- a/build/resources/0ad.sh    2026-01-18 23:38:28.693460280 -0500
++++ b/build/resources/0ad.sh    2026-01-18 23:36:32.725715459 -0500
+@@ -1,9 +1,12 @@
  #!/bin/sh
  
 -pyrogenesis=$(which pyrogenesis 2>/dev/null)
-+gamemoderun=$(command -v gamemoderun 2>/dev/null)
-+mangohud=$(command -v mangohud 2>/dev/null)
-+pyrogenesis=$(command -v pyrogenesis 2>/dev/null)
-+
- if [ -x "$pyrogenesis" ]; then
+-if [ -x "$pyrogenesis" ]; then
 -	"$pyrogenesis" "$@"
-+    if [ -x "$gamemoderun" ] && [ -x "$mangohud" ]; then
-+        "$gamemoderun" "$mangohud" "$pyrogenesis" "$@"
-+    elif [ -x "$gamemoderun" ]; then
-+        "$gamemoderun" "$pyrogenesis" "$@"
-+    elif [ -x "$mangohud" ]; then
-+        "$mangohud" "$pyrogenesis" "$@"
-+    else
-+        "$pyrogenesis" "$@"
-+    fi
- else
+-else
 -	echo "Error: pyrogenesis not found in ($PATH)"
 -	exit 1
-+    echo "Error: pyrogenesis not found in ($PATH)"
-+    exit 1
- fi
+-fi
++pyrogenesis=$(command -v pyrogenesis) || { echo "pyrogenesis not found"; exit 1; }
++gamemoderun=$(command -v gamemoderun)
++mangohud=$(command -v mangohud)
++
++cmd=("$pyrogenesis")
++
++[ -x "$mangohud" ] && cmd=("$mangohud" "${cmd[@]}")
++[ -x "$gamemoderun" ] && cmd=("$gamemoderun" "${cmd[@]}")
++
++exec "${cmd[@]}" "$@"
